Swunmath/Controllers/AppViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Swunmath.Controllers
{
    public class AppViewsController : Controller
    {

        public ActionResult Contacts()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult SocialBoard()
        {
            return View();
        }

        public ActionResult Timeline()
        {
            return View();
        }

        public ActionResult ProfilePage()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult BlogArticle()
        {
            return View();
        }

        public ActionResult Forum()
        {
            return View();
        }

        public ActionResult ForumDetails()
        {
            return View();
        }

        public ActionResult Calendar()
        {
            return View();
        }

        public ActionResult ProjectDetail()
        {
            return View();
        }

        public ActionResult Mailbox()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult FileManager()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult ChatView()
        {
            return View();
        }

        public ActionResult AppPlans()
        {
            return View();
        }

        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Notes()
        {
            return View();
        }

        public ActionResult EmailCompose()
        {
            return View();
        }

        public ActionResult EmailView()
        {
            return View();
        }


    }
}

Swunmath/Controllers/UserController.cs
using Swunmath.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Swunmath.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {
            FormsAuthentication.SignOut();
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string username, string password)
        {
            MembershipUser user = Membership.GetUser(username);
            if (user == null)
            {
                ViewBag.Error = "User does not exist";
                return View("Login");
            }
            else if(user.IsLockedOut)
            {
                ViewBag.Error = "Account has been locked. Please contact the administrator.";
                return View("Login");
            }

            if (Membership.ValidateUser(username, password))
            {
                FormsAuthentication.SetAuthCookie(username, false);
                System.Web.HttpContext.Current.Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(new FormsAuthenticationTicket(1, username, DateTime.Now, DateTime.Now.AddMinutes(20), false, string.Join(",", Roles.GetRolesForUser(username))))));
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                ViewBag.Error = "Invalid username or password";
                return View("Login");
            }
                
        }

        [Route("User/Generatepassword/{EncryyptedID}")]
        public ActionResult Generatepassword(string EncryyptedID)
        {
            Utility U = new Utility();
            MembershipUser user = Membership.GetUser(U.Decrypt(EncryyptedID));
            return View(new UserModel { EmailID = user.Email, IsLocked = user.IsLockedOut, Name = "", Password = "" });
        }

        public ActionResult Changepassword(string UserName, string NewPassword)
        {
            MembershipUser user = Membership.GetUser(UserName);
            user.ChangePassword(user.ResetPassword(), NewPassword);
            return View("ChangeSuccessfull");
        }

        [Authorize(Roles = "admin")]
        public ActionResult ManageUsers()
        {
            string[] users = Roles.GetUsersInRole(ConfigurationManager.AppSettings["AdminRolename"]);
            List<UserModel> usersList = new List<UserModel>();
            MembershipUser LoggedInUser = Membership.GetUser();
            users.ToList().ForEach(X =>
            {
                MembershipUser user = Membership.GetUser(X);
                var profile = System.Web.Profile.ProfileBase.Create(X);
                usersList.Add(new UserModel { Name = Convert.ToString(profile.GetPropertyValue("Name")), CreationDate = user.CreationDate, EmailID = user.Email, IsLocked = user.IsLockedOut, IsLoggedIn = (X == LoggedInUser.UserName) });
            });

            return View(usersList);
        }

        [Authorize(Roles = "admin")]
        public ActionResult AddUser(string UserName)
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult SaveUser(Model.UserModel User)
        {
            MembershipUser user = Membership.GetUser(User.EmailID);
            if (user == null)
            {
                user = Membership.CreateUser(User.EmailID, User.Password, User.EmailID);
                Roles.AddUserToRole(User.EmailID, ConfigurationManager.AppSettings["AdminRolename"]);
                System.Web.Profile.ProfileBase profile = System.Web.Profile.ProfileBase.Create(User.EmailID);
                profile.SetPropertyValue("Name", User.Name);
                profile.Save();
            }
            else
            {
                System.Web.Profile.ProfileBase profile = System.Web.Profile.ProfileBase.Create(User.EmailID);
                profile.SetPropertyValue("Name", User.Name);
                profile.Save();
            }
            return RedirectToAction("ManageUsers");
        }

        public ActionResult PasswordRecovery()
        {
            return View();
        }

        public ActionResult SendRecoveryemail(string UserEmail)
        {
            string Username = Membership.GetUserNameByEmail(UserEmail);
            if (!string.IsNullOrEmpty(Username))
            {
                Utility U = new Utility();
                string Body = "Hello, <br/><br/></br> Please click on the link below to re-generate your password. <br/><br/> <a href='" + string.Format(ConfigurationManager.AppSettings["Passwordrecoverylink"], U.Encrypt(UserEmail) + "'>Click here</a>");

                ViewBag.Message = Utility.SendEmail(UserEmail, Body, ConfigurationManager.AppSettings["RecoverySubject"]) ? "An email with a reset link has been sent to your registered email." : "Some internal error occurred..";
            }
            else
                ViewBag.Message = "Email not registered with us.";

            return View("PasswordRecovery");
        }

        [Authorize(Roles = "admin")]
        public ActionResult LockUnlockUser(string UserName)
        {
            MembershipUser user = Membership.GetUser(UserName);

            if (user.IsLockedOut)
                user.UnlockUser();
            else
            {
                while (!user.IsLockedOut)
                {
                    Membership.ValidateUser(UserName, DateTime.Now.ToString("yyyMMddHHmmss"));
                    user = Membership.GetUser(user.UserName);
                }
            }
            return RedirectToAction("ManageUsers");
        }
    }
}

Swunmath/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        
    </span>
    Copyright © 2019 Swun Math. All rights reserved.
</footer>

Swunmath/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version" style="padding: 6px 10px 0px 6px;">
    <img src="~/Images/swunmath_logo.png" alt="" width="150" height="auto" />
</div>
<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">SWUNMATH</span>
    </div>
    @*<form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            <input type="text" placeholder="Search something special" class="form-control" name="search">
        </div>
    </form>*@
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="" href="@Url.Action("Login", "CommonViews")">Login</a>
                </li>
                <li>
                    <a href="@Url.Action("Login", "CommonViews")">Logout</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("ProfilePage", "AppViews")">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="navbar-right">
        <ul class="nav navbar-nav no-borders">
        </ul>
    </div>
</nav>

Swunmath/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Swunmath | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass()">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Swunmath - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    <aside id="menu">
        @Html.Partial("_Navigation")
    </aside>

    <!-- Main view  -->
    <div id="wrapper">
        @RenderBody()

        <!-- Right Sidebar -->
        @Html.Partial("_Right_Sidebar")

        <!-- Footer-->
        @Html.Partial("_Footer")
    </div>

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Swunmath/Views/Shared/_Layout_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Swunmath | Login</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Swunmath - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    @*<div class="back-link">
        <a href="@Url.Action("Index", "Dashboard")" class="btn btn-primary">Back to Dashboard</a>
    </div>*@

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Swunmath/Views/Shared/_Layout_Boxed.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>HOMER | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass()">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="boxed-wrapper">

        <!-- Header -->
        <div id="header">
            @Html.Partial("_Header")
        </div>

        <!-- Navigation -->
        <aside id="menu">
            @Html.Partial("_Navigation")
        </aside>

        <!-- Main view  -->
        <div id="wrapper">
            @RenderBody()

            <!-- Right Sidebar -->
            @Html.Partial("_Right_Sidebar")

            <!-- Footer-->
            @Html.Partial("_Footer")
        </div>

    </div>

        <!-- Section for main scripts render -->
        @Scripts.Render("~/bundles/jquery/js")
        @Scripts.Render("~/bundles/bootstrap/js")
        @Scripts.Render("~/bundles/homer/js")

        <!-- Handler for local scripts -->
        @RenderSection("scripts", required: false)
</body>
</html>

Swunmath/Views/Shared/_Layout_Landing.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Swunmath | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="landing-page">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Swunmath - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Swunmath/Views/Shared/_Navigation.cshtml
@{ 
    string AdminName = "";
    if (User.Identity.IsAuthenticated)
    {
        MembershipUser user = Membership.GetUser();
        var profile = System.Web.Profile.ProfileBase.Create(user.UserName);
        AdminName = Convert.ToString(profile.GetPropertyValue("Name"));
    }

}
<div id="navigation">
    <div class="profile-picture">
        <img src="~/Images/profile.jpg" class="img-circle m-b" alt="logo">

        <div class="stats-label text-color">
            @*<span class="font-extra-bold font-uppercase">@AdminName</span>*@

            <div class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <small class="text-muted">Administrator</small>
                </a>
               
            </div>
            
        </div>
    </div>

    <ul class="nav metismenu" id="side-menu">
        
        @{
            if (User.IsInRole("admin"))
            {
                <li class="@Html.IsSelected(controller: " Dashboard")">
                    <a href="@Url.Action("Index", "Dashboard" )"> <span class="nav-label"><i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard</span><span class="fa arrow"></span> </a>
                </li>

                <li>
                    <a href="@Url.Action("Category", "CommonViews" )"> <span class="nav-label"><i class="fa fa-list-alt" aria-hidden="true"></i>Category</span><span class="fa arrow"></span> </a>
                </li>
                <li>
                    <a href="@Url.Action("eBook", "CommonViews" )"><span class="nav-label"><i class="fa fa-book" aria-hidden="true"></i>e-Book</span><span class="fa arrow"></span> </a>
                </li>
                <li>
                    <a href="@Url.Action("ManageUsers", "User" )"><span class="nav-label"><i class="fa fa-user" aria-hidden="true"></i> Manage Users</span><span class="fa arrow"></span> </a>
                </li>
            }

            if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a href="@Url.Action("Login", "User" )"><span class="nav-label"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</span><span class="fa arrow"></span> </a>
                </li>
            }
        }
    </ul>
</div>

Swunmath/Views/Shared/_Right_Sidebar.cshtml
<div id="right-sidebar" class="animated fadeInRight">

    <div class="p-m">
        <button id="sidebar-close" class="right-sidebar-toggle sidebar-button btn btn-default m-b-md">
            <i class="pe pe-7s-close"></i>
        </button>
        <div>
            <span class="font-bold no-margins"> Analytics </span>
            <br>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        </div>
        <div class="row m-t-sm m-b-sm">
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">300,102</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
            <div class="col-lg-6">
                <h3 class="no-margins font-extra-bold text-success">280,200</h3>

                <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
            </div>
        </div>
        <div class="progress m-t-xs full progress-small">
            <div style="width: 25%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar"
                 class=" progress-bar progress-bar-success">
                <span class="sr-only">35% Complete (success)</span>
            </div>
        </div>
    </div>
    <div class="p-m bg-light border-bottom border-top">
        <span class="font-bold no-margins"> Social talks </span>
        <br>
        <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
        <div class="m-t-md">
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a1.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">John Novak</span>
                        <small class="text-muted">21.03.2015</small>
                        <div class="social-content small">
                            Injected humour, or randomised words which don't look even slightly believable.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a3.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Mark Smith</span>
                        <small class="text-muted">14.04.2015</small>
                        <div class="social-content">
                            Many desktop publishing packages and web page editors.
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-talk">
                <div class="media social-profile clearfix">
                    <a class="pull-left">
                        <img src="~/Images/a4.jpg" alt="profile-picture">
                    </a>

                    <div class="media-body">
                        <span class="font-bold">Marica Morgan</span>
                        <small class="text-muted">21.03.2015</small>

                        <div class="social-content">
                            There are many variations of passages of Lorem Ipsum available, but the majority have
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="p-m">
        <span class="font-bold no-margins"> Sales in last week </span>
        <div class="m-t-xs">
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$170,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$580,90 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <small>Today</small>
                    <h4 class="m-t-xs">$620,20 <i class="fa fa-level-up text-success"></i></h4>
                </div>
                <div class="col-xs-6">
                    <small>Last week</small>
                    <h4 class="m-t-xs">$140,70 <i class="fa fa-level-up text-success"></i></h4>
                </div>
            </div>
        </div>
        <small>
            Lorem Ipsum is simply dummy text of the printing simply all dummy text.
            Many desktop publishing packages and web page editors.
        </small>
    </div>

</div>

Swunmath/Views/Shared/_Sidemenu.cshtml
<head>
    <title>@Page.Title</title>   
</head>
<div>
    <ul>
        <li><a id="dashboard" href="#">Dashboard</a></li>
        <li><a id="category" href="#">Category</a></li>
        <li><a id="ebook" href="#">e-Book</a></li>
        <li><a id="setting" href="#">Settings</a></li>
    </ul>

</div>

