Swunmath/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Swunmath.Controllers
{
    public class TablesController : Controller
    {
        
        public ActionResult TablesDesign()
        {
            return View();
        }

        public ActionResult DataTables()
        {
            return View();
        }

        public ActionResult FooTable()
        {
            return View();
        }

        public JsonResult tableJsonData()
        {

            // Creat basic JSON object with data for table
            var tableData = new[] 
            {
                new [] { "Tiger Nixon", "System Architect", "Edinburgh", "61", "2011/04/25", "$320,800" },
                new [] { "Garrett Winters", "Accountant", "Tokyo", "63", "2011/07/25", "$170,750" },
                new [] { "Ashton Cox", "Junior Technical Author", "San Francisco", "66", "2009/01/12", "$86,000" },
                new [] { "Cedric Kelly", "Senior Javascript Developer", "Edinburgh", "22", "2012/03/29", "$433,060" },
                new [] { "Airi Satou", "Accountant", "Tokyo", "33", "2008/11/28", "$162,700" },
                new [] { "Brielle Williamson", "Integration Specialist", "New York", "61", "2012/12/02", "$372,000" },
                new [] { "Herrod Chandler", "Sales Assistant", "San Francisco", "59", "2012/08/06", "$137,500" },
                new [] { "Rhona Davidson", "Integration Specialist", "Tokyo", "55", "2010/10/14", "$327,900" },
                new [] { "Colleen Hurst", "Javascript Developer", "San Francisco", "39", "2009/09/15", "$205,500" },
                new [] { "Sonya Frost", "Software Engineer", "Edinburgh", "23", "2008/12/13", "$103,600" },
                new [] { "Jena Gaines", "Office Manager", "London", "30", "2008/12/19", "$90,560" },
                new [] { "Quinn Flynn", "Support Lead", "Edinburgh", "22", "2013/03/03", "$342,000" }
            };

            var dataTable = 
                new {data = tableData} 
            ;

            // Return JSON object
            return Json(dataTable, JsonRequestBehavior.AllowGet);

        }

    }
}

Swunmath/Controllers/UserController.cs
using Swunmath.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Swunmath.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {
            FormsAuthentication.SignOut();
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string username, string password)
        {
            MembershipUser user = Membership.GetUser(username);
            if (user == null)
            {
                ViewBag.Error = "User does not exist";
                return View("Login");
            }
            else if(user.IsLockedOut)
            {
                ViewBag.Error = "Account has been locked. Please contact the administrator.";
                return View("Login");
            }

            if (Membership.ValidateUser(username, password))
            {
                FormsAuthentication.SetAuthCookie(username, false);
                System.Web.HttpContext.Current.Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(new FormsAuthenticationTicket(1, username, DateTime.Now, DateTime.Now.AddMinutes(20), false, string.Join(",", Roles.GetRolesForUser(username))))));
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                ViewBag.Error = "Invalid username or password";
                return View("Login");
            }
                
        }

        [Route("User/Generatepassword/{EncryyptedID}")]
        public ActionResult Generatepassword(string EncryyptedID)
        {
            Utility U = new Utility();
            MembershipUser user = Membership.GetUser(U.Decrypt(EncryyptedID));
            return View(new UserModel { EmailID = user.Email, IsLocked = user.IsLockedOut, Name = "", Password = "" });
        }

        public ActionResult Changepassword(string UserName, string NewPassword)
        {
            MembershipUser user = Membership.GetUser(UserName);
            user.ChangePassword(user.ResetPassword(), NewPassword);
            return View("ChangeSuccessfull");
        }

        [Authorize(Roles = "admin")]
        public ActionResult ManageUsers()
        {
            string[] users = Roles.GetUsersInRole(ConfigurationManager.AppSettings["AdminRolename"]);
            List<UserModel> usersList = new List<UserModel>();
            MembershipUser LoggedInUser = Membership.GetUser();
            users.ToList().ForEach(X =>
            {
                MembershipUser user = Membership.GetUser(X);
                var profile = System.Web.Profile.ProfileBase.Create(X);
                usersList.Add(new UserModel { Name = Convert.ToString(profile.GetPropertyValue("Name")), CreationDate = user.CreationDate, EmailID = user.Email, IsLocked = user.IsLockedOut, IsLoggedIn = (X == LoggedInUser.UserName) });
            });

            return View(usersList);
        }

        [Authorize(Roles = "admin")]
        public ActionResult AddUser(string UserName)
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult SaveUser(Model.UserModel User)
        {
            MembershipUser user = Membership.GetUser(User.EmailID);
            if (user == null)
            {
                user = Membership.CreateUser(User.EmailID, User.Password, User.EmailID);
                Roles.AddUserToRole(User.EmailID, ConfigurationManager.AppSettings["AdminRolename"]);
                System.Web.Profile.ProfileBase profile = System.Web.Profile.ProfileBase.Create(User.EmailID);
                profile.SetPropertyValue("Name", User.Name);
                profile.Save();
            }
            else
            {
                System.Web.Profile.ProfileBase profile = System.Web.Profile.ProfileBase.Create(User.EmailID);
                profile.SetPropertyValue("Name", User.Name);
                profile.Save();
            }
            return RedirectToAction("ManageUsers");
        }

        public ActionResult PasswordRecovery()
        {
            return View();
        }

        public ActionResult SendRecoveryemail(string UserEmail)
        {
            string Username = Membership.GetUserNameByEmail(UserEmail);
            if (!string.IsNullOrEmpty(Username))
            {
                Utility U = new Utility();
                string Body = "Hello, <br/><br/></br> Please click on the link below to re-generate your password. <br/><br/> <a href='" + string.Format(ConfigurationManager.AppSettings["Passwordrecoverylink"], U.Encrypt(UserEmail) + "'>Click here</a>");

                ViewBag.Message = Utility.SendEmail(UserEmail, Body, ConfigurationManager.AppSettings["RecoverySubject"]) ? "An email with a reset link has been sent to your registered email." : "Some internal error occurred..";
            }
            else
                ViewBag.Message = "Email not registered with us.";

            return View("PasswordRecovery");
        }

        [Authorize(Roles = "admin")]
        public ActionResult LockUnlockUser(string UserName)
        {
            MembershipUser user = Membership.GetUser(UserName);

            if (user.IsLockedOut)
                user.UnlockUser();
            else
            {
                while (!user.IsLockedOut)
                {
                    Membership.ValidateUser(UserName, DateTime.Now.ToString("yyyMMddHHmmss"));
                    user = Membership.GetUser(user.UserName);
                }
            }
            return RedirectToAction("ManageUsers");
        }
    }
}

Swunmath/Views/User/AddUser.cshtml
@model Swunmath.Model.UserModel

@{
    ViewBag.Title = "Add User";
}

@using (Html.BeginForm("SaveUser", "User", FormMethod.Post))
{
    <div class="col-lg-10">
        <div class="hpanel">
            <div class="panel-heading">
                Add User
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Name:</label>
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", id = "Name" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Email:</label>
                            @Html.TextBoxFor(m => m.EmailID, new { @class = "form-control", id = "EmailID" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Password:</label>
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", id = "Password" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Re-enter password:</label>
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", id = "ConfirmPassword" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2">
                        <input class="btn btn-default" type="button" onclick="Cancel()" value="Cancel" />
                        @*<button class="btn btn-default" type="submit">Cancel</button>*@
                        <input class="btn btn-primary" type="submit" value="Save Changes" onclick="return Validate()" />
                        @*<button class="btn btn-primary" type="submit">Save Changes</button>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function Cancel() {
        history.go(-1);
    }

    function Validate() {
        if ($("#Name").val().trim() == "") {
            alert("Please enter the name of the user.");
            return false;
        }

        var pattern = /^\b[A-Z0-9._%-]+@@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i
        
        if (!pattern.test($("#EmailID").val().trim())) {
            alert("Please enter a valid email Id.");
            return false;
        }

        if ($("#Password").val().trim() == "") {
            alert("Please provide a password for the user.");
            return false;
        }

        if ($("#Password").val().trim() != $("#ConfirmPassword").val().trim()) {
            alert("Password does not match with the confirm password.");
            return false;
        }

        return true;
    }
</script>

Swunmath/Views/User/ChangeSuccessfull.cshtml

@{
    ViewBag.Title = "Change Successfull";
    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
}

<div class="alert alert-success">
    <strong>Success!</strong> Your password has been changed successfully. @Html.ActionLink("Click here",
                 "Login", 
                 "CommonViews", 
                 null, 
                 null 
                 ) to login.
</div>

Swunmath/Views/User/Generatepassword.cshtml
@model Swunmath.Model.UserModel

@{
    ViewBag.Title = "Generate password";
    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
}

@using (Html.BeginForm("Changepassword", "User"))
{
    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <img src="~/Images/swunmath_logo.png" alt="" width="250" height="auto" />
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <h3>Password <strong>Recover</strong></h3>
                        <div style="background: #6a6c6f;width: 105px;height:5px;display: block;margin-bottom: 22px;"></div>
                        <form action="#" id="loginForm">
                            <input type="hidden" value="@Model.EmailID" name="UserName" class="hidden" />
                            <div class="form-group">
                                <label class="control-label" for="username">New Password</label>
                                <input type="password" title="Please enter the new password" name="NewPassword" id="Newpwd" class="form-control">
                                <span class="help-block small">Your new password</span>
                            </div>

                            <button type="submit" class="btn btn-success btn-xl btn-block" style="background: #004730; padding: 7px;font-size: 20px;margin-top: 20px;" onclick="return Validate();">
                                Change password
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    }

<script>
    function Validate() {
        if ($("#Newpwd").val().trim() == "") {
            alert("Please enter the new password.");
            return false;
        }
        return true;
    }
</script>

Swunmath/Views/User/Login.cshtml
@{
    /**/

    /**/

    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
    //ViewBag.Title = "Login";
}


<style>
    body {
        background: url('../Content/img/loginBac.jpg');
        object-fit: cover;
        background-position: center center;
    }

    .color-line {
        display: none;
    }

    .hpanel .panel-body {
        border-radius: 20px;
        box-shadow: 0px 0px 10px #999;
    }
</style>
@using (Html.BeginForm("LogIn", "User"))
{
    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <img src="~/Images/swunmath_logo.png" alt="" width="250" height="auto" />
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <h3>Admin Panel <strong>Login</strong></h3>
                        <div style="background: #6a6c6f;width: 130px;height:5px;display: block;margin-bottom: 22px;"></div>
                        <form action="#" id="loginForm">
                            <div class="form-group">
                                <input type="text" placeholder="Email" title="Please enter your email" required="" value="" name="username" id="username" class="form-control" style="padding:20px 10px;">
                            </div>
                            <div class="form-group">
                                <input type="password" title="Please enter your password" placeholder="Password" required="" value="" name="password" id="password" class="form-control" style="padding:20px 10px;">
                            </div>
                            <div class="checkbox">
                                <input type="checkbox" class="i-checks" name="Rememberme" checked>
                                Remember me

                                <div class="pull-right">
                                    <a href="/User/PasswordRecovery">Forgot Password?</a>
                                </div>
                            </div>
                            <div class="form-group alert-danger">
                                @(Convert.ToString(ViewBag.Error))
                            </div>
                            <button type="submit" class="btn btn-success btn-xl btn-block" onclick="return Validate()" style="background: #004730; padding: 7px;font-size: 20px;margin-top: 20px;">
                                Login
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
}
<div class="row" style="position:fixed;bottom:10px;width:100%;">
    <div class="col-md-12 text-center">
        Copyright © 2019 Swun Math. All rights reserved.
    </div>
</div>

<script>
    function Validate() {
        var pattern = /^\b[A-Z0-9._%-]+@@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;

        if (!pattern.test($("#username").val().trim())) {
            alert("Please enter the valid Email Id of the user.");
            return false;
        }

        if ($("#password").val().trim() == "") {
            alert("Please enter the password.")
            return false;
        }
        return true;
    }
</script>

Swunmath/Views/User/ManageUsers.cshtml
@model IEnumerable<Swunmath.Model.UserModel>
    @{
        ViewBag.Title = "ManageUsers";
    }

    <div class="content">
        <div class="row">
            <div class="col-lg-12">

                <div class="hpanel">
                    <div class="panel-heading">
                        View Manage User
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <button class="btn btn-info" style="float:right;" onclick="location.href='@Url.Action("AddUser", "User",new { UserName = "" })'">+ Add</button><br /><br />
                            <table id="example2" class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>S.No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Created On</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ int a = 0;}
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@(a += 1)</td>
                                            <td>@item.Name</td>
                                            <td>@item.EmailID</td>
                                            <td>@item.CreationDate.ToString("MM/dd/yyyy")</td>
                                            <td>@if(!@item.IsLoggedIn){<button  onclick="location.href='@Url.Action("LockUnlockUser", "User", new { UserName = item.EmailID })'" class="btn btn-info">@(item.IsLocked ? "Activate" : "Inactivate")</button>}</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

    @section Styles {
        @Styles.Render("~/bundles/datatables/css")
    }

    @section Scripts {
        @Scripts.Render("~/bundles/datatables/js")
        @Scripts.Render("~/bundles/datatablesBootstrap/js")
        @Scripts.Render("~/bundles/datatablesPlugins/js")

        <script type="text/javascript">

        $(function () {

            // JSON data
            var chartDataUrl = '@Url.Action("tableJsonData", "Tables")';

            // Initialize Example 1
            $('#example1').dataTable({
                "ajax": chartDataUrl,
                dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                buttons: [
                    { extend: 'copy', className: 'btn-sm' },
                    { extend: 'csv', title: 'ExampleFile', className: 'btn-sm' },
                    { extend: 'pdf', title: 'ExampleFile', className: 'btn-sm' },
                    { extend: 'print', className: 'btn-sm' }
                ]
            });

            // Initialize Example 2
            $('#example2').dataTable();

        });

        </script>
    }




Swunmath/Views/User/PasswordRecovery.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
    ViewBag.Title = "Password Recovery";
}

<style>
    body {
        background: url('../Content/img/loginBac.jpg');
        object-fit: cover;
        background-position: center center;
    }

    .color-line {
        display: none;
    }

    .hpanel .panel-body {
        border-radius: 20px;
        box-shadow: 0px 0px 10px #999;
    }
</style>

@using (Html.BeginForm("SendRecoveryemail", "User"))
{
    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <img src="~/Images/swunmath_logo.png" alt="" width="250" height="auto" />
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <h3>Password <strong>Recover</strong></h3>
                        <div style="background: #6a6c6f;width: 105px;height:5px;display: block;margin-bottom: 22px;"></div>
                        <form action="#" id="loginForm">
                            <div class="form-group">
                                <label class="control-label" for="username">Email</label>
                                <input type="text" placeholder="example@gmail.com" title="Please enter you email adress" required="" value="" name="UserEmail" id="username" class="form-control">
                                <span class="help-block small">Your registered email address</span>
                            </div>

                            <button type="submit" class="btn btn-success btn-xl btn-block" style="background: #004730; padding: 7px;font-size: 20px;margin-top: 20px;" onclick="return Validate();">
                                Reset password
                            </button>                            
                        </form>
                        
                    </div>
                </div>
                @if (ViewBag.Message != "")
                {
                    <span class="alert alert-danger">@ViewBag.Message</span>
                }
            </div>
        </div>
    </div>
   
}
<div class="row" style="position:fixed;bottom:10px;width:100%;">
    <div class="col-md-12 text-center">
        Copyright © 2019 Swun Math. All rights reserved.
    </div>
</div>

<script>
    function Validate() {
        var pattern = /^\b[A-Z0-9._%-]+@@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;
        if (!pattern.test($("#username").val().trim())) {
            alert("Please enter the valid Email Id of the user.");
            return false;
        }
        else
            return true;
    }
</script>